language: python
python:
  - "3.6"
sudo: false
cache: pip

install:
  - "pip install ."

script:
  - cd example; bash bootstrap.sh test; cd ..
  - cd doc; make html; cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/_build/html
  on:
    branch: master

matrix:
  allow_failures:
    - script: cd doc; make html; cd ..

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false
