language: python
python:
  - "3.6"
sudo: false
cache: pip

install:
  - "pip install ."

script:
  - nosetests
  - cd docs; make html; make clean; cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/_build/html
  on:
    branch: master

# deploy:
#   provider: pypi
#   user: "MingxuanZhang"
#   password: "mussles-sspipeline"
#   distributions: "sdist bdist_wheel"

matrix:
  allow_failures:
    - script: cd docs; make html; make clean; cd ..

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false
