language: python
python:
  - "3.6"

sudo: false

install:
  - "pip install . -r requirements.txt"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - pipeline --help
  - pipeline --version
  - bash tests/test_pipeline.sh
  - cat tests/output/pipeline.log
  - black *.py -l 79 --check; black */*.py -l 79 --check
  - pycodestyle *.py --format=pylint --verbose; pycodestyle */*.py --format=pylint --verbose
  - sphinx-apidoc -fo docs/source pipeline
  - sphinx-build -b html docs/source docs/build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master

deploy:
  provider: pypi
  user: "MingxuanZhang"
  password: "mussles-sspipeline"
  distributions: "sdist bdist_wheel"

matrix:
  allow_failures:
    - script: sphinx-apidoc -fo docs/source pipeline
    - script: sphinx-build -b html docs/source docs/build

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false