language: python

python:
  - 2.7
  - 3.5
  - 3.6

cache: pip

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - pip install pip --upgrade

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - python setup.py install

script:
  - pipeline --help
  - pipeline --version
  - bash pipeline/tests/test_pipeline.sh
  - cat pipeline/tests/pipeline.log

notifications:
  slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
  email: false