language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
cache: pip

install:
  - "pip install . -r requirements.txt"

script:
  - nosetests
  - sphinx-apidoc -fo docs/source sspipeline
  - sphinx-build -b html docs/source docs/build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master

# deploy:
#   provider: pypi
#   user: "MingxuanZhang"
#   password: "mussles-sspipeline"
#   distributions: "sdist bdist_wheel"

matrix:
  allow_failures:
    - script: sphinx-apidoc -fo docs/source sspipeline
    - script: sphinx-build -b html docs/source docs/build

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false