language: python
python:
  - "3.6"

sudo: false

install:
  - "pip install . -r requirements.txt"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - pipeline --help
  - pipeline --version
  - bash pipeline/tests/test_pipeline.sh
  - cat pipeline/tests/pipeline.log
  - sphinx-apidoc -fo docs/source pyxem
  - sphinx-build -b html docs/source docs/build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master

matrix:
  allow_failures:
    - script: sphinx-apidoc -fo docs/source pyxem
    - script: sphinx-build -b html docs/source docs/build

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false