# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
os: linux

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7-dev

before_install:
  # Additional info about the build
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Install from environment
  - conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/full_test.yaml
  - source activate test

    # Build and install package
  - python setup.py develop --no-deps

script:
    - pipeline --help
    - pipeline --version
    - bash pipeline/tests/test_pipeline.sh
    - cat pipeline/tests/pipeline.log
    - flake8 pipeline
    - if [[ $DOCS == 'true' ]]; then source .ci/build_docs.sh; fi

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        condition: $DOCS = 'true'

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false