language: generic
os: linux

jobs:
  fast_finish: true
  include:
    - env:
      - PYTHON=2.7
      - DOCS='false'
    - env:
      - PYTHON=3.4
      - DOCS='false'
    - env:
      - PYTHON=3.5
      - DOCS='false'
    - env:
      - PYTHON=3.6
      - DOCS='true'
    - env:
      - PYTHON=3.6
      - DOCS='false'
      os: osx

install:
    - source ci/install.sh;

script:
    - pipeline --help
    - pipeline --version
    - bash pipeline/tests/test_pipeline.sh
    - cat pipeline/tests/pipeline.log
    - flake8 pipeline
    - if [[ $DOCS == 'true' ]]; then source ci/build_docs.sh; fi

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        condition: $DOCS = 'true'